version: 2
jobs:
  records_build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/work
    steps:
      - checkout
      - run:
          command: |
            cd records_mod
            python main.py
      - persist_to_workspace:
          root: records_mod
          paths:
            - records
  webui_build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/work
    steps:
      - checkout
      - attach_workspace:
          at: records_mod
      - run:
          command: |
            cp records_mod/records/*.json webui/src
            cd webui
            npm build
  deploy:
    
