version: 2
jobs:
  records_build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/work
    steps:
      - checkout
      - run:
          command: |
            sudo pip install -r requirements.txt
            cd records_mod
            python main.py
            cd -
          no_output_timeout: 20m
      - persist_to_workspace:
          root: records_mod
          paths:
            - records
  webui_build_from_ws:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/work
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            cp -rf records_mod/records webui/src
            cd webui
            sudo npm install
            sudo npm run build
      - persist_to_workspace:
          root: webui
          paths:
            - build
  webui_build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/work
    steps:
      - checkout
      - run:
          command: |
            cp -rf records_mod/records webui/src
            cd webui
            sudo npm install
            sudo npm run build
      - persist_to_workspace:
          root: webui
          paths:
            - build
  deploy:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/work
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "e5:f7:07:ca:a4:5c:76:22:db:ba:db:23:1c:ae:b8:95"
      - run:
          name: deploy
          command: |
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git clone git@github.com:ted027/ted027.github.io public
            rm -rf public/records/* public/static/* public/manifest.json
            cp -rp build/* public/records
            mv public/records/manifest.json public
            mv public/records/static/* public/static
            cd public && ls -al
            cd records && ls -al
            cd ../../
      - run:
          mame: push
          command: |
            cd public
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
            git add --all
            msg="update records `date`"
            git commit -m "$msg"
            git push origin master

workflows:
  version: 2
  normal_build:
    jobs:
      - webui_build
      - deploy:
          requires:
            - webui_build
  # nightly_build:
  #   triggers:
  #     - schedule:
  #         cron: "20 15 * * *"
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - records_build
  #     - webui_build_from_ws:
  #         requires:
  #           - records_build
  #     - deploy:
  #         requires:
  #           - webui_build_from_ws