version: 2
jobs:
  records_build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/work
    steps:
      - checkout
      # - run:
      #     command: |
      #       pip install -r requirements.txt
      #       cd records_mod
      #       python main.py
      #
      - persist_to_workspace:
          root: records_mod
          paths:
            - records
  webui_build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/work
    steps:
      - checkout
      - attach_workspace:
          at: records_mod
      - run:
          command: |
            cp -rf records_mod/records webui/src
            cd webui
            sudo npm install
            sudo npm run build
      - persist_to_workspace:
          root: webui
          paths:
            - build
  deploy:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/work
    steps:
      - attach_workspace:
          at: build
      - add_ssh_keys:
          fingerprints:
            - "e5:f7:07:ca:a4:5c:76:22:db:ba:db:23:1c:ae:b8:95"
      - run:
          name: deploy
          command: |
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git clone git@github.com:ted027/ted027.github.io public
            rm -rf public/records public/static public/manifest.json
            cp build/* public/records
            mv public/records/manifest.json public
            mv public/records/static public/static
      - run:
          mame: push
          command: |
            cd public
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
            git add --all
            msg="update records `date`"
            git commit -m "$msg"
            git push origin master

workflows:
  version: 2
  normal_build:
    jobs:
      - records_build
      - webui_build:
          requires:
            - records_build
      - deploy:
          requires:
            - webui_build