version: 2
jobs:
  records_build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: prepare
          command: |
            sudo sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/' /etc/ssl/openssl.cnf
            pip install -r ./records_mod/requirements.txt -t ./records_mod/lib
      - run:
          name: records build
          command: |
            cd records_mod
            rm -rf records/2020/*
            cd lib
            ls
            cd -
            export PYTHONPATH=$PWD/lib:$PYTHONPATH
            python main.py
            cd -            
          no_output_timeout: 10m
      - add_ssh_keys:
          fingerprints:
            - "e5:f7:07:ca:a4:5c:76:22:db:ba:db:23:1c:ae:b8:95"
      - run:
          name: records push
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
            git add --all
            msg="nightly update records `date`"
            git commit -m "$msg"
            git push origin master
  webui_build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: webui build
          command: |
            cp -rf records_mod/records/2020/* webui/src/records/2020
            cp -rf webui/src/records/2020/parks.json webui/src/records
            cd webui
            sudo npm install
            sudo npm run build
      - persist_to_workspace:
          root: webui
          paths:
            - build
  deploy:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/work
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "e5:f7:07:ca:a4:5c:76:22:db:ba:db:23:1c:ae:b8:95"
      - run:
          name: webui deploy
          command: |
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git clone git@github.com:ted027/ted027.github.io public
            rm -rf public/records/* public/static/* public/manifest.json
            cp -rp build/* public/records
            mv public/records/manifest.json public
            mv public/records/static/* public/static
      - run:
          mame: webui push
          command: |
            cd public
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
            git add --all
            msg="update records webui `date`"
            git commit -m "$msg"
            git push origin master

workflows:
  version: 2
  normal_build:
    jobs:
      - records_build
      # - webui_build:
      #     filters:
      #         branches:
      #           only: master
      # - deploy:
      #     filters:
      #         branches:
      #           only: master
      #     requires:
      #       - webui_build
  nightly_build:
    triggers:
      - schedule:
          cron: "0,40 14 * * *"
          filters:
            branches:
              only: master
    jobs:
      - records_build
